import type { Metadata } from "next";
import "./globals.css";
import SideBarWrapper from "./components/SidebarWrapper";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <SideBarWrapper/>
          <main className="flex-1 p-6 ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
